### ISSUE TITLE
News records lack "add media file" button

### ISSUE THREAD

**Issue by kitzberger** [georgringer/faker#15]
The "add media file" button is missing when EXT:faker is installed.

| Not installed | Installed |
| -- | -- |
| ![Bildschirmfoto vom 2022-07-06 13-31-29](https://user-images.githubusercontent.com/1405149/177540654-ac73df90-0b7e-4e7b-92f7-5d8d65ecc5ca.png) | ![Bildschirmfoto vom 2022-07-06 13-34-37](https://user-images.githubusercontent.com/1405149/177541201-d4c22c85-c697-4e92-95c3-b992c542885a.png) | 

Apparently that's due to this line. Why is that line present anyways?

https://github.com/georgringer/faker/blob/a2479ccdf799b45bf180c266845899c6199bcb38/Configuration/TCA/Overrides/tx_news_domain_model_news.php#L8

Does it do anything? Maybe just an accidential left over?

**Comment by baschny** [comment]
The idea is probably that with faker in an environment, you won't add files manually to your records anymore. But since the use-case is very strict, I would simply remove this restriction.

And maybe do a 2.0.0 release after that change, since we also changed compatible TYPO3 versions in the meantime since the "1.0.0" release back in 2020.

@kitzberger pull request?

**Comment by kitzberger** [comment]
> The idea is probably that with faker in an environment, you won't add files manually to your records anymore.

But fal_related_files remained untouched? Seems odd to me ;-)
