### ISSUE TITLE
Error on execution of bin/typo3 after installation

### ISSUE THREAD

**Issue by manuelselbach** [georgringer/faker#26]
I get prompted by the following error message, when I try to run the command or any other after installation:

```
PHP Fatal error:  Declaration of GeorgRinger\Faker\Command\FakerCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/georgringer/faker/Classes/Command/FakerCommand.php on line 70

Fatal error: Declaration of GeorgRinger\Faker\Command\FakerCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/georgringer/faker/Classes/Command/FakerCommand.php on line 70
Failed to run typo3 help: exit status 255
```

TYPO3 Version 12.4.20
PHP 8.3.10

**Comment by baschny** [comment]
Good catch. This one is peculiar, because the interface changed between Symfony 6 and 7, and TYPO3 v12 supports both.

If you have PHP 8.2 it will install symfony/console v7 (which requires the `:int`), while if you have TYPO3 v12 on PHP 8.1, it will install symfony/console v6 (which has no `:int` in the signature, and thus would crash with a similar message).

So in order to support v12, we will have to rise the PHP requirement to PHP 8.2 (or simply require `symfony/console:^7`).

I think that makes sense, and we would then also drop support for TYPO3 v11. And maybe also add support for v13 (also Symfony v7).

**Comment by manuelselbach** [comment]
Sounds like a plan. If I can support here, let me know 😊

**Comment by baschny** [comment]
My mistake! Adding the `:int` will still work also with the old interface with PHP 8.1, so the change can be done without breaking anything.

If you can provide the pull request, I can merge that. Thanks!

**Comment by manuelselbach** [comment]
Here you go.
